export const REQUEST_COMMENT = 'REQUEST_COMMENT';
export const REQUEST_COMMENT_SUCCESS = 'REQUEST_COMMENT_SUCCESS';
export const REQUEST_COMMENT_ERROR = 'REQUEST_COMMENT_ERROR';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';

// export const DELETE_COMMENT = 'DELETE_COMMENT';
// export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
// export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';

export const LIKE_COMMENT = 'LIKE_COMMENT';
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS';
export const LIKE_COMMENT_ERROR = 'LIKE_COMMENT_ERROR';
