export const REQUEST_SNIPPETS = 'REQUEST_SNIPPETS';
export const REQUEST_SNIPPETS_SUCCESS = 'REQUEST_SNIPPETS_SUCCESS';
export const REQUEST_SNIPPETS_ERROR = 'REQUEST_SNIPPETS_ERROR';

export const ADD_SNIPPET = 'ADD_SNIPPET';
export const ADD_SNIPPET_SUCCESS = 'ADD_SNIPPET_SUCCESS';
export const ADD_SNIPPET_ERROR = 'ADD_SNIPPET_ERROR';

export const DELETE_SNIPPET = 'DELETE_SNIPPET';
export const DELETE_SNIPPET_SUCCESS = 'DELETE_SNIPPET_SUCCESS';
export const DELETE_SNIPPET_ERROR = 'DELETE_SNIPPET_ERROR';
