export const REQUEST_SNIPPETS = 'REQUEST_SNIPPETS';
export const REQUEST_SNIPPETS_SUCCESS = 'REQUEST_SNIPPETS_SUCCESS';
export const REQUEST_SNIPPETS_ERROR = 'REQUEST_SNIPPETS_ERROR';

export const ADD_SNIPPET = 'ADD_SNIPPET';
export const ADD_SNIPPET_SUCCESS = 'ADD_SNIPPET_SUCCESS';
export const ADD_SNIPPET_ERROR = 'ADD_SNIPPET_ERROR';

export const DELETE_SNIPPET = 'DELETE_SNIPPET';
export const DELETE_SNIPPET_SUCCESS = 'DELETE_SNIPPET_SUCCESS';
export const DELETE_SNIPPET_ERROR = 'DELETE_SNIPPET_ERROR';

export const LIKE_SNIPPET = 'LIKE_SNIPPET';
export const LIKE_SNIPPET_SUCCESS = 'LIKE_SNIPPET_SUCCESS';
export const LIKE_SNIPPET_ERROR = 'LIKE_SNIPPET_ERROR';

export const REQUEST_RECOMMENDED_SNIPPETS = 'REQUEST_RECOMMENDED_SNIPPETS';
export const REQUEST_RECOMMENDED_SNIPPETS_SUCCESS = 'REQUEST_RECOMMENDED_SNIPPETS_SUCCESS';
export const REQUEST_RECOMMENDED_SNIPPETS_ERROR = 'REQUEST_RECOMMENDED_SNIPPETS_ERROR';

export const REQUEST_HOT_SNIPPETS = 'REQUEST_HOT_SNIPPETS';
export const REQUEST_HOT_SNIPPETS_SUCCESS = 'REQUEST_HOT_SNIPPETS_SUCCESS';
export const REQUEST_HOT_SNIPPETS_ERROR = 'REQUEST_HOT_SNIPPETS_ERROR';

export const REQUEST_NEWEST_SNIPPETS = 'REQUEST_NEWEST_SNIPPETS';
export const REQUEST_NEWEST_SNIPPETS_SUCCESS = 'REQUEST_NEWEST_SNIPPETS_SUCCESS';
export const REQUEST_NEWEST_SNIPPETS_ERROR = 'REQUEST_NEWEST_SNIPPETS_ERROR';